name: CD - Deploy Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET }}
        aws-region: ap-southeast-1
    
    - name: Create deployment package
      run: |
        pip install -r requirements.txt -t ./package
        cp main.py flight_agent.py itinerary_agent.py travel_llm.py ./package/
        cd package
        zip -r ../lambda_deployment.zip .
        cd ..
    
    - name: Update Lambda function code
      run: |
        aws lambda update-function-code \
          --function-name travel_assistant \
          --zip-file fileb://lambda_deployment.zip
    
    - name: Update Lambda function configuration
      run: |
        aws lambda update-function-configuration \
          --function-name travel_assistant \
          --environment "Variables={GROQ_API_KEY=${{ secrets.GROQ_API_KEY }},PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }},AMADEUS_ID=${{ secrets.AMADEUS_ID }},AMADEUS_SECRET=${{ secrets.AMADEUS_SECRET }}}"